export const PRODUCTS =[
    {
        id:0,
        name:"FRENCH BRIE CHEESE",
        image:"/FoodShop/assets/images/Frenchcheese.png",
        info:"I'm a product detail. I'm a great place to add more information about your product such as sizing, material, care and cleaning instructions. This is also a great space to write what makes this product special and how your customers can benefit from this item. Buyers like to know what they’re getting before they purchase, so give them as much information as possible so they can buy with confidence and certainty.",
        description:"I'm a product description. I’m a great place to include more information about your product. Buyers like to know what they’re getting before they purchase.",
        price:6.99,
        oldPrice:6.99,
        featured:true,
        new:false,
        sale:true,
        sku:"0001",
        type:"cheese"
    },
    {
        id:1,
        name:"CHEESE 1",
        image:"/FoodShop/assets/images/Cheese1.png",
        info:"I'm a product detail. I'm a great place to add more information about your product such as sizing, material, care and cleaning instructions. This is also a great space to write what makes this product special and how your customers can benefit from this item. Buyers like to know what they’re getting before they purchase, so give them as much information as possible so they can buy with confidence and certainty.",
        description:"I'm a product description. I’m a great place to include more information about your product. Buyers like to know what they’re getting before they purchase.",
        price:8.99,
        oldPrice:8.99,
        featured:false,
        new:false,
        sale:false,
        sku:"0002",
        type:"cheese"
    },
    {
        id:2,
        name:"CHEESE 2",
        image:"/FoodShop/assets/images/Cheese2.png",
        info:"I'm a product detail. I'm a great place to add more information about your product such as sizing, material, care and cleaning instructions. This is also a great space to write what makes this product special and how your customers can benefit from this item. Buyers like to know what they’re getting before they purchase, so give them as much information as possible so they can buy with confidence and certainty.",
        description:"I'm a product description. I’m a great place to include more information about your product. Buyers like to know what they’re getting before they purchase.",
        price:6.99,
        oldPrice:6.99,
        featured:false,
        new:true,
        sale:false,
        sku:"0003",
        type:"cheese"
    },
    {
        id:3,
        name:"CHEESE 3",
        image:"/FoodShop/assets/images/Cheese3.png",
        info:"I'm a product detail. I'm a great place to add more information about your product such as sizing, material, care and cleaning instructions. This is also a great space to write what makes this product special and how your customers can benefit from this item. Buyers like to know what they’re getting before they purchase, so give them as much information as possible so they can buy with confidence and certainty.",
        description:"I'm a product description. I’m a great place to include more information about your product. Buyers like to know what they’re getting before they purchase.",
        price:9.99,
        oldPrice:6.99,
        featured:false,
        new:false,
        sale:false,
        sku:"0004",
        type:"cheese"
    },
    {
        id:4,
        name:"SMOKED VIRGINIA BACON",
        image:"/FoodShop/assets/images/Smokebacon.png",
        info:"I'm a product detail. I'm a great place to add more information about your product such as sizing, material, care and cleaning instructions. This is also a great space to write what makes this product special and how your customers can benefit from this item. Buyers like to know what they’re getting before they purchase, so give them as much information as possible so they can buy with confidence and certainty.",
        description:"I'm a product description. I’m a great place to include more information about your product. Buyers like to know what they’re getting before they purchase.",
        price:12.99,
        oldPrice:12.99,
        featured:true,
        new:false,
        sale:false,
        sku:"0005",
        type:"meat"
    },
    {
        id:5,
        name:"MEAT 1",
        image:"/FoodShop/assets/images/Meat1.png",
        info:"I'm a product detail. I'm a great place to add more information about your product such as sizing, material, care and cleaning instructions. This is also a great space to write what makes this product special and how your customers can benefit from this item. Buyers like to know what they’re getting before they purchase, so give them as much information as possible so they can buy with confidence and certainty.",
        description:"I'm a product description. I’m a great place to include more information about your product. Buyers like to know what they’re getting before they purchase.",
        price:22.99,
        oldPrice:22.99,
        featured:false,
        new:false,
        sale:false,
        sku:"0006",
        type:"meat"
    },
    {
        id:6,
        name:"MEAT 2",
        image:"/FoodShop/assets/images/Meat2.png",
        info:"I'm a product detail. I'm a great place to add more information about your product such as sizing, material, care and cleaning instructions. This is also a great space to write what makes this product special and how your customers can benefit from this item. Buyers like to know what they’re getting before they purchase, so give them as much information as possible so they can buy with confidence and certainty.",
        description:"I'm a product description. I’m a great place to include more information about your product. Buyers like to know what they’re getting before they purchase.",
        price:12.99,
        oldPrice:12.99,
        featured:false,
        new:true,
        sale:false,
        sku:"0007",
        type:"meat"
    },
    {
        id:7,
        name:"MEAT 3",
        image:"/FoodShop/assets/images/Meat3.png",
        info:"I'm a product detail. I'm a great place to add more information about your product such as sizing, material, care and cleaning instructions. This is also a great space to write what makes this product special and how your customers can benefit from this item. Buyers like to know what they’re getting before they purchase, so give them as much information as possible so they can buy with confidence and certainty.",
        description:"I'm a product description. I’m a great place to include more information about your product. Buyers like to know what they’re getting before they purchase.",
        price:6.74,
        oldPrice:8.99,
        featured:false,
        new:false,
        sale:true,
        sku:"0008",
        type:"meat"
    },
    {
        id:8,
        name:"GREEK KALAMATA OLIVES",
        image:"/FoodShop/assets/images/Greekolives.png",
        info:"I'm a product detail. I'm a great place to add more information about your product such as sizing, material, care and cleaning instructions. This is also a great space to write what makes this product special and how your customers can benefit from this item. Buyers like to know what they’re getting before they purchase, so give them as much information as possible so they can buy with confidence and certainty.",
        description:"I'm a product description. I’m a great place to include more information about your product. Buyers like to know what they’re getting before they purchase.",
        price:8.99,
        oldPrice:8.99,
        featured:true,
        new:false,
        sale:false,
        sku:"0009",
        type:"provision"
    },
    {
        id:9,
        name:"PROVISION 1",
        image:"/FoodShop/assets/images/Provision1.png",
        info:"I'm a product detail. I'm a great place to add more information about your product such as sizing, material, care and cleaning instructions. This is also a great space to write what makes this product special and how your customers can benefit from this item. Buyers like to know what they’re getting before they purchase, so give them as much information as possible so they can buy with confidence and certainty.",
        description:"I'm a product description. I’m a great place to include more information about your product. Buyers like to know what they’re getting before they purchase.",
        price:10.99,
        oldPrice:10.99,
        featured:false,
        new:false,
        sale:false,
        sku:"0010",
        type:"provision"
    },
    {
        id:10,
        name:"PROVISION 2",
        image:"/FoodShop/assets/images/Provision2.png",
        info:"I'm a product detail. I'm a great place to add more information about your product such as sizing, material, care and cleaning instructions. This is also a great space to write what makes this product special and how your customers can benefit from this item. Buyers like to know what they’re getting before they purchase, so give them as much information as possible so they can buy with confidence and certainty.",
        description:"I'm a product description. I’m a great place to include more information about your product. Buyers like to know what they’re getting before they purchase.",
        price:9.99,
        oldPrice:9.99,
        featured:false,
        new:false,
        sale:false,
        sku:"0011",
        type:"provision"
    },
    {
        id:11,
        name:"PROVISION 3",
        image:"/FoodShop/assets/images/Provision3.png",
        info:"I'm a product detail. I'm a great place to add more information about your product such as sizing, material, care and cleaning instructions. This is also a great space to write what makes this product special and how your customers can benefit from this item. Buyers like to know what they’re getting before they purchase, so give them as much information as possible so they can buy with confidence and certainty.",
        description:"I'm a product description. I’m a great place to include more information about your product. Buyers like to know what they’re getting before they purchase.",
        price:22.99,
        oldPrice:22.99,
        featured:false,
        new:false,
        sale:false,
        sku:"0012",
        type:"provision"
    }
]